Added an install test to the test suite
It does a dry run of python setup.py install. This checks that all the
references in setup.py are correct.

diff --git a/tests/install_test b/tests/install_test
--- a/tests/install_test
+++ b/tests/install_test
@@ -19,26 +19,23 @@
 # Authors:
 #   Martin Preisler <mpreisle@redhat.com>
 
-# parent dir of this script
+echo -n -e "Running install test\t\t...\t"
+
 PARENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-pushd $PARENT_DIR > /dev/null
 
-PYTHON_VERSIONS="$(which python2 2> /dev/null) $(which python3 2> /dev/null)"
+EXIT_CODE=0
 
-for PYTHON in $PYTHON_VERSIONS;
-do
-    echo "Testing with python '$PYTHON'"
+pushd $PARENT_DIR/.. > /dev/null
+output=`$PYTHON setup.py --dry-run install 2>&1`
+if [ "$?" == "0" ]; then
+    echo "[ pass ]"
+else
+    echo "[ FAIL ]"
     echo
-    export PYTHON
-
-    ./unit/make_check || exit 1
+    echo "$output"
     echo
-    ./integration/make_check || exit 1
-    echo
-    ./install_test || exit 1
-    echo
-
-    echo
-done
-
+    EXIT_CODE=1
+fi
 popd > /dev/null
+
+exit $EXIT_CODE
