Moved unit tests to a separate dir, tests/make_check runs all tests

diff --git a/tests/unit/make_check b/tests/unit/make_check
--- a/tests/unit/make_check
+++ b/tests/unit/make_check
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 # Copyright 2015 Red Hat Inc., Durham, North Carolina.
 # All Rights Reserved.
 #
@@ -17,4 +19,34 @@
 # Authors:
 #   Martin Preisler <mpreisle@redhat.com>
 
-all = ["test_utils"]
+echo "Running unit tests..."
+echo
+
+# parent dir of this script
+PARENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+pushd $PARENT_DIR
+
+# add directory with "unit" to $PYTHONPATH
+export PYTHONPATH=$PARENT_DIR/tests/unit:$PYTHONPATH
+
+RUNWRAPPER_NO_FORK=1 source ../../runwrapper.sh
+
+EXIT_CODE=0
+for file in test_*.py
+do
+    echo -n -e "$file\t\t...\t"
+    output=`./$file 2>&1`
+    if [ "$?" == "0" ]; then
+        echo "[ pass ]"
+    else
+        echo "[ FAIL ]"
+        echo
+        echo "$output"
+        echo
+        EXIT_CODE=1
+    fi
+done
+
+popd
+
+exit $EXIT_CODE
